### ISSUE TITLE
composer versions with "v"

### ISSUE THREAD

**Issue by szepeviktor** [dependencies-io/support#27] opened 2018-05-08 19:28 UTC
knplabs/knp-snappy https://packagist.org/packages/knplabs/knp-snappy has a lot of 1.* versions prefixed with a *v*

dependencies.io urges to update `^1.0` to 0.4.3

Please advise.

**Comment by davegaeddert** [comment] 2018-05-08 19:34
Can you point me towards your repo? It's possible that the `v` is the problem, but more often the issue is that you should use `--ignore-platform-reqs` in the `composer_options` setting (see the [docs](https://www.dependencies.io/docs/dependencies/php/) and [related issue](https://github.com/dependencies-io/php/issues/18)). We've seen a couple cases where, because of the php version used in our container, some dependencies get downgraded without `--ignore-platform-reqs`.

Feel free to use the chat in the bottom right corner of the site to talk privately, but if you can point me towards your repo then we can get to the bottom of it. Thanks!

**Comment by szepeviktor** [comment] 2018-05-08 19:38
Hello Dave!

`https://app.dependencies.io/projects/gitlab/gallerytool/gallerytool`

I haven't touched your codebase as I'm trying to assess your project.

**Comment by szepeviktor** [comment] 2018-05-08 19:39
> the chat in the bottom right corner of the site to

It went for a sleep, no chat icon...

**Comment by davegaeddert** [comment] 2018-05-08 19:44
Strange... You can email support@dependencies.io then.

We're considering making `--ignore-platform-reqs` a default for php, but until then, you'd need to put a `dependencies.yml` file in place to see if that is the issue.

Something like this for, for the php part at least:
```yml
version: 2
dependencies:
- type: php
  settings:
    composer_options: "--ignore-platform-reqs"
```

I understand you're trying to assess it and haven't put a config in place yet. We do our best to make everything "just work" out of the box, but as you can imagine, projects can vary quite a bit so sometimes a `dependencies.yml` is required to get the behavior you're looking for.

Happy to talk further, here or over email.

**Comment by szepeviktor** [comment] 2018-05-08 19:49
> Happy to talk further, here or over email.

Thank you for your answer.

We develop and run our CI on PHP 7.2

**Comment by davegaeddert** [comment] 2018-05-08 19:58
We will look into this, but since you're project has been removed we'll keep track of it in the php repo and close this.

**Closed by davegaeddert** 2018-05-08 19:58 UTC

**Comment by szepeviktor** [comment] 2018-05-08 20:00
OK!

**Comment by szepeviktor** [comment] 2018-05-08 20:02
Here? https://github.com/dependencies-io/php

**Comment by davegaeddert** [comment] 2018-05-08 20:08
Just made an issue here: https://github.com/dependencies-io/php/issues/20
